--
-------------------------------------------------------------------------------------------
-- Copyright © 2010-2013, Xilinx, Inc.
-- This file contains confidential and proprietary information of Xilinx, Inc. and is
-- protected under U.S. and international copyright and other intellectual property laws.
-------------------------------------------------------------------------------------------
--
-- Disclaimer:
-- This disclaimer is not a license and does not grant any rights to the materials
-- distributed herewith. Except as otherwise provided in a valid license issued to
-- you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
-- MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
-- DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
-- INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
-- OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
-- (whether in contract or tort, including negligence, or under any other theory
-- of liability) for any loss or damage of any kind or nature related to, arising
-- under or in connection with these materials, including for any direct, or any
-- indirect, special, incidental, or consequential loss or damage (including loss
-- of data, profits, goodwill, or any type of loss or damage suffered as a result
-- of any action brought by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-safe, or for use in any
-- application requiring fail-safe performance, such as life-support or safety
-- devices or systems, Class III medical devices, nuclear facilities, applications
-- related to the deployment of airbags, or any other applications that could lead
-- to death, personal injury, or severe property or environmental damage
-- (individually and collectively, "Critical Applications"). Customer assumes the
-- sole risk and liability of any use of Xilinx products in Critical Applications,
-- subject only to applicable laws and regulations governing limitations on product
-- liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
--
-------------------------------------------------------------------------------------------
--
--
-- Production template for a 0.125K program (128 instructions) for KCPSM6 in a Spartan-6, 
-- Virtex-6 or 7-Series device using 9 Slices.
--
-- Note: The full 12-bit KCPSM6 address is connected but only the lower 7-bits will be 
--       employed. Likewise the 'bram_enable' should still be connected to 'enable'. 
--       This minimises the changes required to the hardware description of a design 
--       when moving between different memory types and selecting different sizes.
--
--            program_rom: your_program
--              port map(     address => address,      
--                        instruction => instruction,
--                             enable => bram_enable,
--                                clk => clk);
--
--
-- Program defined by 'C:\Users\allison.122.ASC\Box\firmware\arty_eth_test\ethernet\src\hycontrol\hycontrol_picoblaze_rom_v2.psm'.
--
-- Generated by KCPSM6 Assembler: 25 Jan 2020 - 10:57:31. 
--
-- Assembler used ROM_form template: ROM_form_128_14March13.vhd
--
--
-- Standard IEEE libraries
--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--
-- The Unisim Library is used to define Xilinx primitives. It is also used during
-- simulation. The source can be viewed at %XILINX%\vhdl\src\unisims\unisim_VCOMP.vhd
--  
library unisim;
use unisim.vcomponents.all;
--
--
entity hycontrol_picoblaze_rom_v2 is
    Port (      address : in std_logic_vector(11 downto 0);
            instruction : out std_logic_vector(17 downto 0);
                 enable : in std_logic;
                    clk : in std_logic);
    end hycontrol_picoblaze_rom_v2;
--
architecture low_level_definition of hycontrol_picoblaze_rom_v2 is
--
signal rom_value : std_logic_vector(17 downto 0);
--
begin
  --
  instruction_bit: for i in 0 to 17 generate
  begin
    --
    kcpsm6_rom_flop: FDRE
    port map (  D => rom_value(i),
                Q => instruction(i),
               CE => enable,
                R => address(7+(i/4)),
                C => clk);
    --
  end generate instruction_bit;
  --
  --
  kcpsm6_rom0: ROM128X1
  generic map( INIT => X"00000192C39D025B2C554ABCDB53E460")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(0));
  --
  kcpsm6_rom1: ROM128X1
  generic map( INIT => X"000000010381024C3CDDFBBA91622400")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(1));
  --
  kcpsm6_rom2: ROM128X1
  generic map( INIT => X"0000001801C60C643005CAEB55006500")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(2));
  --
  kcpsm6_rom3: ROM128X1
  generic map( INIT => X"00000001008000441017CFAF1B000100")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(3));
  --
  kcpsm6_rom4: ROM128X1
  generic map( INIT => X"000000411464B51483AA141028048000")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(4));
  --
  kcpsm6_rom5: ROM128X1
  generic map( INIT => X"000000181001080C4AE0002008001010")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(5));
  --
  kcpsm6_rom6: ROM128X1
  generic map( INIT => X"000000790040A81809420457F6001095")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(6));
  --
  kcpsm6_rom7: ROM128X1
  generic map( INIT => X"00000000020602081410000000380000")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(7));
  --
  kcpsm6_rom8: ROM128X1
  generic map( INIT => X"000001004A0C0521D420815092E8019D")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(8));
  --
  kcpsm6_rom9: ROM128X1
  generic map( INIT => X"000000001C000122E000810524F01A40")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(9));
  --
  kcpsm6_rom10: ROM128X1
  generic map( INIT => X"0000018000060720C630810000400000")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(10));
  --
  kcpsm6_rom11: ROM128X1
  generic map( INIT => X"0000000000000000C000000000000000")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(11));
  --
  kcpsm6_rom12: ROM128X1
  generic map( INIT => X"00000386E33F57AB36B8B155B6FBB0F7")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(12));
  --
  kcpsm6_rom13: ROM128X1
  generic map( INIT => X"0000000108CFF0DC418D7AAB6D06CC08")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(13));
  --
  kcpsm6_rom14: ROM128X1
  generic map( INIT => X"0000024530600124800489DDB7847F19")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(14));
  --
  kcpsm6_rom15: ROM128X1
  generic map( INIT => X"000000619C3F51EBC089B355B6F9BC9D")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(15));
  --
  kcpsm6_rom16: ROM128X1
  generic map( INIT => X"00000183F040006700058BFFFF846720")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(16));
  --
  kcpsm6_rom17: ROM128X1
  generic map( INIT => X"0000025D20CFF9DC89CF7EAA4904DC19")
  port map( A0 => address(0),
            A1 => address(1),
            A2 => address(2),
            A3 => address(3),
            A4 => address(4),
            A5 => address(5),
            A6 => address(6),
             O => rom_value(17));
  --
  --
end low_level_definition;
--
------------------------------------------------------------------------------------
--
-- END OF FILE hycontrol_picoblaze_rom_v2.vhd
--
------------------------------------------------------------------------------------
